LOCAL_PATH          :=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE        := NxGammaTest
LOCAL_SRC_FILES     := app/NxGammaTest/NxGammaTest.apk
LOCAL_MODULE_PATH   := $(TARGET_OUT_APPS)
LOCAL_MODULE_CLASS  := APPS
LOCAL_MODULE_OWNER  := nexell
LOCAL_MODULE_TAGS   := optional
LOCAL_CERTIFICATE   := PRESIGNED
LOCAL_MODULE_SUFFIX   := $(COMMON_ANDROID_PACKAGE_SUFFIX)


include $(BUILD_PREBUILT)

